// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

public final class ObjetoRemoto_Stub
    extends java.rmi.server.RemoteStub
    implements IObjetoRemoto, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_EnviaAlias_0;
    private static java.lang.reflect.Method $method_EnviaMensaje_1;
    private static java.lang.reflect.Method $method_RecibeAlias1_2;
    private static java.lang.reflect.Method $method_RecibeAlias2_3;
    private static java.lang.reflect.Method $method_RecibeMensaje1_4;
    private static java.lang.reflect.Method $method_RecibeMensaje2_5;
    
    static {
	try {
	    $method_EnviaAlias_0 = IObjetoRemoto.class.getMethod("EnviaAlias", new java.lang.Class[] {java.lang.String.class, int.class});
	    $method_EnviaMensaje_1 = IObjetoRemoto.class.getMethod("EnviaMensaje", new java.lang.Class[] {java.lang.String.class, int.class});
	    $method_RecibeAlias1_2 = IObjetoRemoto.class.getMethod("RecibeAlias1", new java.lang.Class[] {});
	    $method_RecibeAlias2_3 = IObjetoRemoto.class.getMethod("RecibeAlias2", new java.lang.Class[] {});
	    $method_RecibeMensaje1_4 = IObjetoRemoto.class.getMethod("RecibeMensaje1", new java.lang.Class[] {});
	    $method_RecibeMensaje2_5 = IObjetoRemoto.class.getMethod("RecibeMensaje2", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public ObjetoRemoto_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of EnviaAlias(String, int)
    public void EnviaAlias(java.lang.String $param_String_1, int $param_int_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_EnviaAlias_0, new java.lang.Object[] {$param_String_1, new java.lang.Integer($param_int_2)}, -7942638549723181202L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of EnviaMensaje(String, int)
    public void EnviaMensaje(java.lang.String $param_String_1, int $param_int_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_EnviaMensaje_1, new java.lang.Object[] {$param_String_1, new java.lang.Integer($param_int_2)}, 8395459658897293997L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of RecibeAlias1()
    public java.lang.String RecibeAlias1()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_RecibeAlias1_2, null, 5883151152367886796L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of RecibeAlias2()
    public java.lang.String RecibeAlias2()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_RecibeAlias2_3, null, 5039964465138016598L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of RecibeMensaje1()
    public java.lang.String RecibeMensaje1()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_RecibeMensaje1_4, null, 6640695234967638453L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of RecibeMensaje2()
    public java.lang.String RecibeMensaje2()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_RecibeMensaje2_5, null, -3200616557032970583L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
